language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "nightly"  # nightly build
  
# command to install dependencies
install:
  - pip install -r requirements.txt
  - cd social_distribution && python3 manage.py makemigrations && cd ../
  - cd social_distribution && python3 manage.py migrate --run-syncdb && cd ../

# command to run tests
script:
  - cd social_distribution
  - python3 manage.py test