language: python
python:
  - "3.6"
cache:
  yarn: true
  pip: true
install:
  - pip install -r requirements.txt
  - yarn install
script:
  - python manage.py makemigrations --dry-run | grep 'No changes detected' || (echo 'There are changes which require migrations.' && exit 1)
  - py.test backend/
  - yarn test

# Send notification to Slack on deploy
notifications:
  slack: cmput404team2:X4ovyEEbhpnyz8PzuK0KYrIG
